spring:
  application:
  name: userservice
server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:https://localhost:8888/eureka/

